// Code generated by "stringer -type=irqmask -output=interrupts_string.go -trimprefix=irq"; DO NOT EDIT.

package cyw43439

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[irqDATA_UNAVAILABLE-1]
	_ = x[irqF2_F3_FIFO_RD_UNDERFLOW-2]
	_ = x[irqF2_F3_FIFO_WR_OVERFLOW-4]
	_ = x[irqCOMMAND_ERROR-8]
	_ = x[irqDATA_ERROR-16]
	_ = x[irqF2_PACKET_AVAILABLE-32]
	_ = x[irqF3_PACKET_AVAILABLE-64]
	_ = x[irqF1_OVERFLOW-128]
	_ = x[irqMISC_INTR0-256]
	_ = x[irqMISC_INTR1-512]
	_ = x[irqMISC_INTR2-1024]
	_ = x[irqMISC_INTR3-2048]
	_ = x[irqMISC_INTR4-4096]
	_ = x[irqF1_INTR-8192]
	_ = x[irqF2_INTR-16384]
	_ = x[irqF3_INTR-32768]
}

const _irqmask_name = "DATA_UNAVAILABLEF2_F3_FIFO_RD_UNDERFLOWF2_F3_FIFO_WR_OVERFLOWCOMMAND_ERRORDATA_ERRORF2_PACKET_AVAILABLEF3_PACKET_AVAILABLEF1_OVERFLOWMISC_INTR0MISC_INTR1MISC_INTR2MISC_INTR3MISC_INTR4F1_INTRF2_INTRF3_INTR"

var _irqmask_map = map[irqmask]string{
	1:     _irqmask_name[0:16],
	2:     _irqmask_name[16:39],
	4:     _irqmask_name[39:61],
	8:     _irqmask_name[61:74],
	16:    _irqmask_name[74:84],
	32:    _irqmask_name[84:103],
	64:    _irqmask_name[103:122],
	128:   _irqmask_name[122:133],
	256:   _irqmask_name[133:143],
	512:   _irqmask_name[143:153],
	1024:  _irqmask_name[153:163],
	2048:  _irqmask_name[163:173],
	4096:  _irqmask_name[173:183],
	8192:  _irqmask_name[183:190],
	16384: _irqmask_name[190:197],
	32768: _irqmask_name[197:204],
}

func (i irqmask) String() string {
	if str, ok := _irqmask_map[i]; ok {
		return str
	}
	return "irqmask(" + strconv.FormatInt(int64(i), 10) + ")"
}
