// Code generated by "stringer -type=AsyncEventType -output=asyncevent_type_string.go -trimprefix=CYW43_EV_"; DO NOT EDIT.

package whd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CYW43_EV_SET_SSID-0]
	_ = x[CYW43_EV_JOIN-1]
	_ = x[CYW43_EV_AUTH-3]
	_ = x[CYW43_EV_DEAUTH-5]
	_ = x[CYW43_EV_DEAUTH_IND-6]
	_ = x[CYW43_EV_ASSOC-7]
	_ = x[CYW43_EV_DISASSOC-11]
	_ = x[CYW43_EV_DISASSOC_IND-12]
	_ = x[CYW43_EV_LINK-16]
	_ = x[CYW43_EV_PRUNE-23]
	_ = x[CYW43_EV_PSK_SUP-46]
	_ = x[CYW43_EV_IF-54]
	_ = x[CYW43_EV_P2P_DISC_LISTEN_COMPLETE-55]
	_ = x[CYW43_EV_RSSI-56]
	_ = x[CYW43_EV_ESCAN_RESULT-69]
	_ = x[CYW43_EV_CSA_COMPLETE_IND-80]
	_ = x[CYW43_EV_ASSOC_REQ_IE-87]
	_ = x[CYW43_EV_ASSOC_RESP_IE-88]
}

const _AsyncEventType_name = "SET_SSIDJOINAUTHDEAUTHDEAUTH_INDASSOCDISASSOCDISASSOC_INDLINKPRUNEPSK_SUPIFP2P_DISC_LISTEN_COMPLETERSSIESCAN_RESULTCSA_COMPLETE_INDASSOC_REQ_IEASSOC_RESP_IE"

var _AsyncEventType_map = map[AsyncEventType]string{
	0:  _AsyncEventType_name[0:8],
	1:  _AsyncEventType_name[8:12],
	3:  _AsyncEventType_name[12:16],
	5:  _AsyncEventType_name[16:22],
	6:  _AsyncEventType_name[22:32],
	7:  _AsyncEventType_name[32:37],
	11: _AsyncEventType_name[37:45],
	12: _AsyncEventType_name[45:57],
	16: _AsyncEventType_name[57:61],
	23: _AsyncEventType_name[61:66],
	46: _AsyncEventType_name[66:73],
	54: _AsyncEventType_name[73:75],
	55: _AsyncEventType_name[75:99],
	56: _AsyncEventType_name[99:103],
	69: _AsyncEventType_name[103:115],
	80: _AsyncEventType_name[115:131],
	87: _AsyncEventType_name[131:143],
	88: _AsyncEventType_name[143:156],
}

func (i AsyncEventType) String() string {
	if str, ok := _AsyncEventType_map[i]; ok {
		return str
	}
	return "AsyncEventType(" + strconv.FormatInt(int64(i), 10) + ")"
}
