// Code generated by "stringer -type=SDPCMCommand -output=sdpcm_command_string.go -trimprefix=WLC_"; DO NOT EDIT.

package whd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WLC_UP-2]
	_ = x[WLC_SET_INFRA-20]
	_ = x[WLC_SET_AUTH-22]
	_ = x[WLC_GET_BSSID-23]
	_ = x[WLC_GET_SSID-25]
	_ = x[WLC_SET_SSID-26]
	_ = x[WLC_SET_CHANNEL-30]
	_ = x[WLC_DISASSOC-52]
	_ = x[WLC_GET_ANTDIV-63]
	_ = x[WLC_SET_ANTDIV-64]
	_ = x[WLC_SET_DTIMPRD-78]
	_ = x[WLC_GET_PM-85]
	_ = x[WLC_SET_PM-86]
	_ = x[WLC_SET_GMODE-110]
	_ = x[WLC_SET_WSEC-134]
	_ = x[WLC_SET_BAND-142]
	_ = x[WLC_GET_ASSOCLIST-159]
	_ = x[WLC_SET_WPA_AUTH-165]
	_ = x[WLC_SET_VAR-263]
	_ = x[WLC_GET_VAR-262]
	_ = x[WLC_SET_WSEC_PMK-268]
}

const _SDPCMCommand_name = "UPSET_INFRASET_AUTHGET_BSSIDGET_SSIDSET_SSIDSET_CHANNELDISASSOCGET_ANTDIVSET_ANTDIVSET_DTIMPRDGET_PMSET_PMSET_GMODESET_WSECSET_BANDGET_ASSOCLISTSET_WPA_AUTHGET_VARSET_VARSET_WSEC_PMK"

var _SDPCMCommand_map = map[SDPCMCommand]string{
	2:   _SDPCMCommand_name[0:2],
	20:  _SDPCMCommand_name[2:11],
	22:  _SDPCMCommand_name[11:19],
	23:  _SDPCMCommand_name[19:28],
	25:  _SDPCMCommand_name[28:36],
	26:  _SDPCMCommand_name[36:44],
	30:  _SDPCMCommand_name[44:55],
	52:  _SDPCMCommand_name[55:63],
	63:  _SDPCMCommand_name[63:73],
	64:  _SDPCMCommand_name[73:83],
	78:  _SDPCMCommand_name[83:94],
	85:  _SDPCMCommand_name[94:100],
	86:  _SDPCMCommand_name[100:106],
	110: _SDPCMCommand_name[106:115],
	134: _SDPCMCommand_name[115:123],
	142: _SDPCMCommand_name[123:131],
	159: _SDPCMCommand_name[131:144],
	165: _SDPCMCommand_name[144:156],
	262: _SDPCMCommand_name[156:163],
	263: _SDPCMCommand_name[163:170],
	268: _SDPCMCommand_name[170:182],
}

func (i SDPCMCommand) String() string {
	if str, ok := _SDPCMCommand_map[i]; ok {
		return str
	}
	return "SDPCMCommand(" + strconv.FormatInt(int64(i), 10) + ")"
}
