// Code generated by "stringer -type=SDPCMCommand -output=sdpcm_command_string.go -trimprefix=WLC_"; DO NOT EDIT.

package whd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WLC_UP-2]
	_ = x[WLC_DOWN-3]
	_ = x[WLC_SET_INFRA-20]
	_ = x[WLC_SET_AUTH-22]
	_ = x[WLC_GET_BSSID-23]
	_ = x[WLC_GET_SSID-25]
	_ = x[WLC_SET_SSID-26]
	_ = x[WLC_SET_CHANNEL-30]
	_ = x[WLC_DISASSOC-52]
	_ = x[WLC_GET_ANTDIV-63]
	_ = x[WLC_SET_ANTDIV-64]
	_ = x[WLC_SET_DTIMPRD-78]
	_ = x[WLC_GET_PM-85]
	_ = x[WLC_SET_PM-86]
	_ = x[WLC_SET_GMODE-110]
	_ = x[WLC_SET_AP-118]
	_ = x[WLC_SET_WSEC-134]
	_ = x[WLC_SET_BAND-142]
	_ = x[WLC_GET_ASSOCLIST-159]
	_ = x[WLC_SET_WPA_AUTH-165]
	_ = x[WLC_SET_VAR-263]
	_ = x[WLC_GET_VAR-262]
	_ = x[WLC_SET_WSEC_PMK-268]
}

const _SDPCMCommand_name = "UPDOWNSET_INFRASET_AUTHGET_BSSIDGET_SSIDSET_SSIDSET_CHANNELDISASSOCGET_ANTDIVSET_ANTDIVSET_DTIMPRDGET_PMSET_PMSET_GMODESET_APSET_WSECSET_BANDGET_ASSOCLISTSET_WPA_AUTHGET_VARSET_VARSET_WSEC_PMK"

var _SDPCMCommand_map = map[SDPCMCommand]string{
	2:   _SDPCMCommand_name[0:2],
	3:   _SDPCMCommand_name[2:6],
	20:  _SDPCMCommand_name[6:15],
	22:  _SDPCMCommand_name[15:23],
	23:  _SDPCMCommand_name[23:32],
	25:  _SDPCMCommand_name[32:40],
	26:  _SDPCMCommand_name[40:48],
	30:  _SDPCMCommand_name[48:59],
	52:  _SDPCMCommand_name[59:67],
	63:  _SDPCMCommand_name[67:77],
	64:  _SDPCMCommand_name[77:87],
	78:  _SDPCMCommand_name[87:98],
	85:  _SDPCMCommand_name[98:104],
	86:  _SDPCMCommand_name[104:110],
	110: _SDPCMCommand_name[110:119],
	118: _SDPCMCommand_name[119:125],
	134: _SDPCMCommand_name[125:133],
	142: _SDPCMCommand_name[133:141],
	159: _SDPCMCommand_name[141:154],
	165: _SDPCMCommand_name[154:166],
	262: _SDPCMCommand_name[166:173],
	263: _SDPCMCommand_name[173:180],
	268: _SDPCMCommand_name[180:192],
}

func (i SDPCMCommand) String() string {
	if str, ok := _SDPCMCommand_map[i]; ok {
		return str
	}
	return "SDPCMCommand(" + strconv.FormatInt(int64(i), 10) + ")"
}
